import { abril, nunito } from "./fonts";
import "./style/globals.scss";

import Header from "./layout/header";

export const metadata = {
  title: "Moreporfavor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${abril.variable} ${nunito.variable}`}>
      <body>
        {/* Typescript error with handling async server components */}
        <Header />

        <main className="mt-23">{children}</main>
      </body>
    </html>
  );
}
