import { abril, nunito } from "./fonts";
import "./style/globals.scss";

import Header from "./layout/header";
import Footer from "./layout/footer";

export const metadata = {
  title: "Moreporfavor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${abril.variable} ${nunito.variable}`}>
      <body>
        <Header />
        <main className="mt-23">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
